import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Whatsapp 2.0</title>
        <meta name="description" content="Generated by TooHuynh" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello World</h1>
    </div>
  );
};

export default Home;
